{
  "uid" : "4b4757e66a1912dae1a509f688f20b0f",
  "children" : [ {
    "name" : "Test defects",
    "children" : [ {
      "name" : "TypeError: get_block_by_hash() got an unexpected keyword argument 'req_id'",
      "children" : [ {
        "name" : "test_rpc_call_eth_getBlockByHash",
        "uid" : "af62e08c5654e078",
        "parentUid" : "1c7616b7b1a579ecae9c31185965cdbf",
        "status" : "broken",
        "time" : {
          "start" : 1646757688845,
          "stop" : 1646757693626,
          "duration" : 4781
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ ]
      } ],
      "uid" : "1c7616b7b1a579ecae9c31185965cdbf"
    }, {
      "name" : "TypeError: fromhex() argument must be str, not HexBytes",
      "children" : [ {
        "name" : "test_rpc_call_eth_sendRawTransaction",
        "uid" : "5af4ded64e2ff90d",
        "parentUid" : "e9bac02ca83e196007c7b2ebb952161b",
        "status" : "broken",
        "time" : {
          "start" : 1646757775768,
          "stop" : 1646757778035,
          "duration" : 2267
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ ]
      } ],
      "uid" : "e9bac02ca83e196007c7b2ebb952161b"
    } ],
    "uid" : "bdbf199525818fae7a8651db9eafe741"
  }, {
    "name" : "Product defects",
    "children" : [ {
      "name" : "AssertionError: <AssertMessage.CONTAINS_ERROR: 'Contains the error data'>\nassert False\n +  where False = <bound method BasicHelpers.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7f2cfd5c1b80>>(JsonRpcErrorResponse(id=14, error={'code': -32000, 'message': 'Missing data'}, jsonrpc='2.0'))\n +    where <bound method BasicHelpers.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7f2cfd5c1b80>> = <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7f2cfd5c1b80>.assert_no_error_object",
      "children" : [ {
        "name" : "test_rpc_call_eth_call",
        "uid" : "87bc01a29de8c285",
        "parentUid" : "44e2449c2bfb578355957592fff0dc80",
        "status" : "failed",
        "time" : {
          "start" : 1646757712382,
          "stop" : 1646757718348,
          "duration" : 5966
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ ]
      } ],
      "uid" : "44e2449c2bfb578355957592fff0dc80"
    }, {
      "name" : "AssertionError: <AssertMessage.CONTAINS_ERROR: 'Contains the error data'>\nassert False\n +  where False = <bound method BasicHelpers.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7f2cfd1c9d30>>(JsonRpcErrorResponse(id=15, error={'code': -32000, 'message': \"'NoneType' object is not subscriptable\"}, jsonrpc='2.0'))\n +    where <bound method BasicHelpers.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7f2cfd1c9d30>> = <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7f2cfd1c9d30>.assert_no_error_object",
      "children" : [ {
        "name" : "test_rpc_call_eth_estimateGas",
        "uid" : "10b2f4c685071660",
        "parentUid" : "5d98fc38452f188a2e95212d35b9298d",
        "status" : "failed",
        "time" : {
          "start" : 1646757718357,
          "stop" : 1646757719887,
          "duration" : 1530
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ ]
      } ],
      "uid" : "5d98fc38452f188a2e95212d35b9298d"
    }, {
      "name" : "Failed: Error evaluating 'xfail' condition\n    ERC20 is in progress\n              ^\nSyntaxError: invalid syntax",
      "children" : [ {
        "name" : "test_zero_erc20",
        "uid" : "54a0c6f53d903b55",
        "parentUid" : "46efdb9cbec58f646e68ae167ece314f",
        "status" : "failed",
        "time" : {
          "start" : 1646757827557,
          "stop" : 1646757827557,
          "duration" : 0
        },
        "flaky" : false,
        "newFailed" : true,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ ]
      } ],
      "uid" : "46efdb9cbec58f646e68ae167ece314f"
    } ],
    "uid" : "8fb3a91ba5aaf9de24cc8a92edc82b5d"
  } ],
  "name" : "categories"
}