{
  "uid" : "4b4757e66a1912dae1a509f688f20b0f",
  "children" : [ {
    "name" : "Test defects",
    "children" : [ {
      "name" : "ValueError: {'code': -32000, 'message': 'connection already closed'}",
      "children" : [ {
        "name" : "test_rpc_call_eth_call",
        "uid" : "3484c42df1f8b382",
        "parentUid" : "cf7957bfdb0561efc74ada68d6693cf4",
        "status" : "broken",
        "time" : {
          "start" : 1648019730994,
          "stop" : 1648019731662,
          "duration" : 668
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ ]
      }, {
        "name" : "test_rpc_call_eth_getTransactionReceipt",
        "uid" : "1a2edbae0fb6d72f",
        "parentUid" : "cf7957bfdb0561efc74ada68d6693cf4",
        "status" : "broken",
        "time" : {
          "start" : 1648019853124,
          "stop" : 1648019853792,
          "duration" : 668
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ ]
      } ],
      "uid" : "cf7957bfdb0561efc74ada68d6693cf4"
    } ],
    "uid" : "bdbf199525818fae7a8651db9eafe741"
  }, {
    "name" : "Product defects",
    "children" : [ {
      "name" : "AssertionError: <AssertMessage.CONTAINS_ERROR: 'Contains the error data'>\nassert False\n +  where False = <bound method BasicTests.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7fd08bbaeee0>>(JsonRpcErrorResponse(id=37, error={'code': -32000, 'message': 'connection already closed'}, jsonrpc='2.0'))\n +    where <bound method BasicTests.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7fd08bbaeee0>> = <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7fd08bbaeee0>.assert_no_error_object",
      "children" : [ {
        "name" : "test_rpc_call_eth_getLogs_via_tags[latest-latest]",
        "uid" : "1e3ed2ea6a8afa51",
        "parentUid" : "bb687e21bf4e1aae1cb35e9ae5de558b",
        "status" : "failed",
        "time" : {
          "start" : 1648019733207,
          "stop" : 1648019733917,
          "duration" : 710
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ "'latest'", "'latest'" ]
      } ],
      "uid" : "bb687e21bf4e1aae1cb35e9ae5de558b"
    }, {
      "name" : "AssertionError: <AssertMessage.CONTAINS_ERROR: 'Contains the error data'>\nassert False\n +  where False = <bound method BasicTests.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7fd08bc27e80>>(JsonRpcErrorResponse(id=25, error={'code': -32000, 'message': 'connection already closed'}, jsonrpc='2.0'))\n +    where <bound method BasicTests.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7fd08bc27e80>> = <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7fd08bc27e80>.assert_no_error_object",
      "children" : [ {
        "name" : "test_rpc_call_eth_getLogs_via_tags[pending-latest]",
        "uid" : "2a85082f2c480d31",
        "parentUid" : "72cc34cfdef43f13cabac625a0c95b78",
        "status" : "failed",
        "time" : {
          "start" : 1648019734642,
          "stop" : 1648019735354,
          "duration" : 712
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ "'pending'", "'latest'" ]
      } ],
      "uid" : "72cc34cfdef43f13cabac625a0c95b78"
    }, {
      "name" : "AssertionError: <AssertMessage.CONTAINS_ERROR: 'Contains the error data'>\nassert False\n +  where False = <bound method BasicTests.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7fd08bba8250>>(JsonRpcErrorResponse(id=26, error={'code': -32000, 'message': 'connection already closed'}, jsonrpc='2.0'))\n +    where <bound method BasicTests.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7fd08bba8250>> = <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7fd08bba8250>.assert_no_error_object",
      "children" : [ {
        "name" : "test_rpc_call_eth_getLogs_via_tags[latest-earliest]",
        "uid" : "91f518ba147de143",
        "parentUid" : "0d0bc0dfb7395b774572189f449a4bcf",
        "status" : "failed",
        "time" : {
          "start" : 1648019735361,
          "stop" : 1648019736072,
          "duration" : 711
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ "'latest'", "'earliest'" ]
      } ],
      "uid" : "0d0bc0dfb7395b774572189f449a4bcf"
    }, {
      "name" : "AssertionError: <AssertMessage.CONTAINS_ERROR: 'Contains the error data'>\nassert False\n +  where False = <bound method BasicTests.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7fd08bad0850>>(JsonRpcErrorResponse(id=86, error={'code': -32000, 'message': 'connection already closed'}, jsonrpc='2.0'))\n +    where <bound method BasicTests.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7fd08bad0850>> = <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7fd08bad0850>.assert_no_error_object",
      "children" : [ {
        "name" : "test_rpc_call_eth_getLogs_via_tags[latest-pending]",
        "uid" : "3fad7c9c6d301cd4",
        "parentUid" : "a5526a278b1a2f83ae34c066a9877b5d",
        "status" : "failed",
        "time" : {
          "start" : 1648019736079,
          "stop" : 1648019736791,
          "duration" : 712
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ "'latest'", "'pending'" ]
      } ],
      "uid" : "a5526a278b1a2f83ae34c066a9877b5d"
    }, {
      "name" : "AssertionError: <AssertMessage.CONTAINS_ERROR: 'Contains the error data'>\nassert False\n +  where False = <bound method BasicTests.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7fd08bbaeb50>>(JsonRpcErrorResponse(id=64, error={'code': -32000, 'message': 'connection already closed'}, jsonrpc='2.0'))\n +    where <bound method BasicTests.assert_no_error_object of <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7fd08bbaeb50>> = <integration.tests.basic.test_rpc_calls.TestRpcCalls object at 0x7fd08bbaeb50>.assert_no_error_object",
      "children" : [ {
        "name" : "test_rpc_call_eth_getLogs_via_numbers",
        "uid" : "ce9cc1a5394df6e9",
        "parentUid" : "8c00116931bb8ba8d722f9cc50403245",
        "status" : "failed",
        "time" : {
          "start" : 1648019736798,
          "stop" : 1648019737508,
          "duration" : 710
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ ]
      } ],
      "uid" : "8c00116931bb8ba8d722f9cc50403245"
    }, {
      "name" : "AssertionError: The response type is error response\nassert False\n +  where False = <bound method BasicTests.assert_is_successful_response of <integration.tests.basic.test_transactions.TestRpcCallsTransactions object at 0x7fd08bb1ff10>>(JsonRpcErrorResponse(id=84, error={'code': -32000, 'message': 'connection already closed'}, jsonrpc='2.0'))\n +    where <bound method BasicTests.assert_is_successful_response of <integration.tests.basic.test_transactions.TestRpcCallsTransactions object at 0x7fd08bb1ff10>> = <integration.tests.basic.test_transactions.TestRpcCallsTransactions object at 0x7fd08bb1ff10>.assert_is_successful_response",
      "children" : [ {
        "name" : "test_rpc_call_eth_sendRawTransaction",
        "uid" : "667bd33d2f7a21fa",
        "parentUid" : "a51c603dbe164e4989d45931fc45e8d2",
        "status" : "failed",
        "time" : {
          "start" : 1648019848751,
          "stop" : 1648019849414,
          "duration" : 663
        },
        "flaky" : false,
        "newFailed" : false,
        "newPassed" : false,
        "newBroken" : false,
        "retriesCount" : 0,
        "retriesStatusChange" : false,
        "parameters" : [ ]
      } ],
      "uid" : "a51c603dbe164e4989d45931fc45e8d2"
    } ],
    "uid" : "8fb3a91ba5aaf9de24cc8a92edc82b5d"
  } ],
  "name" : "categories"
}